### ISSUE TITLE
cant change date/time for entries

### ISSUE THREAD

**Issue by MonsterITServices** [waldronmatt/FullCalendar-BS4-PHP-MySQL-JSON#12]
Hi,

I've followed your readme and it appears i cannot edit the date/time for any entry. is this something i've missed or is it a bug? 

not sure i'm running xampp on a windows 10 machine but all files have read write.

**Comment by MonsterITServices** [comment]
Also it takes you to jan 2019. is it possible to take you to todays date instead?

**Comment by waldronmatt** [comment]
setting `defaultDate: new Date()` in index.php/index-json.php should bring you to the current date

for your date/time editing it's tough to determine without seeing your code.

try changing all file/folder permissions to 777 and see if it works (it's not wise to leave these permissions permanently though - security risk)

Let me know if that helps or you're experiencing the same problem.

**Comment by MonsterITServices** [comment]
Found there was a readonly tag at the end of editing option. thanks for the above it has worked.
