### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by TDClarke** [waldronmatt/FullCalendar-BS4-PHP-MySQL-JSON#2]
It would be nice if recurring events could be added to the calendar!

I know this is done slightly differently with V4.x!

**Comment by waldronmatt** [comment]
Hey TDClarke that would be a nice addition. I will mark this as an enhancement and will attempt to implement based on FulLCalendar's limited implementation (pre v4): https://stackoverflow.com/questions/15161654/recurring-events-in-fullcalendar

However, I do have some reservations about server side implementation (load, performance). See this post for clarity: https://github.com/fullcalendar/fullcalendar/issues/387#issuecomment-132527344

**Comment by waldronmatt** [comment]
@TDClarke you can now preview a limited capability of event recurrences by pulling in my branch. I plan on adding more capabilities soon.

Recurrences limited to 2 - 4 weekly recurrences (including all day events) from the date scheduled and series deletion option. Editing recurrences not yet possible. Functionality available only for JSON currently.

**Comment by waldronmatt** [comment]
Weekday recurrences now supported in the latest release: https://github.com/waldronmatt/FullCalendar-BS4-PHP-MySQL-JSON/releases/tag/v1.1.0

Closing this issue.

Monthly, yearly recurrences with MySQL support will be implemented at a future date.
