### ISSUE TITLE
SQL queries

### ISSUE THREAD

**Issue by TDClarke** [waldronmatt/FullCalendar-BS4-PHP-MySQL-JSON#3]
I have been using this code for my project and it's been suggested that the code would be more secure if PDO or MYSQLi where used, as the existing SQL library will be depreciated at some point in the future!

**Comment by waldronmatt** [comment]
That's correct TDClark. To my knowledge no functions exist that are dependent on MYSQL, however the SQL code in this repo should be addressed for security improvements and to prevent SQL injection. I will mark this as an enhancement to be added in the future. 

You are welcome to add to this repo if you'd like to address this issue.

**Comment by waldronmatt** [comment]
Field sanitization added to most recent updates to master. Closing this out.
