### ISSUE TITLE
Resource view?

### ISSUE THREAD

**Issue by Slampan** [waldronmatt/FullCalendar-BS4-PHP-MySQL-JSON#4]
Is there a way to add this?

https://fullcalendar.io/docs/v3/vertical-resource-view

**Comment by waldronmatt** [comment]
Unfortunately, no. Vertical Resource View requires a Full Calendar premium purchase: https://fullcalendar.io/purchase

There are limited repos that mimic vertical view in Github and the majority break on versions exceeding version 2. Closing this issue for now.
