### ISSUE TITLE
Edit event from mobile

### ISSUE THREAD

**Issue by rainpwn** [waldronmatt/FullCalendar-BS4-PHP-MySQL-JSON#8]
Hi!
I've tried to edit an event from mobile (iPhone XS Max iOS 12) but it does not work!
Can you help me?
Thank you in advance!

**Comment by waldronmatt** [comment]
Hi @inside-shellshock probably because touch screen events are not yet supported on this repo. If you'd like to investigate, see FC's wiki: https://fullcalendar.io/docs/v3/touch

Marking as an enhancement for future implementation. Feel free to share/contribute a solution if you're able to able to implement.

**Comment by rainpwn** [comment]
I Fixed replacing **'DBLCLICK'** with **'click'** :
```javascript
eventRender: function(event, element) {
				element.bind('dblclick', function() {
					$('#ModalEdit #id').val(event.id);
					$('#ModalEdit #title').val(event.title);
					$('#ModalEdit #description').val(event.description);
					$('#ModalEdit #color').val(event.color);
					$('#ModalEdit').modal('show');
				});
			},
```
Like that
```javascript
eventRender: function(event, element) {
				element.bind('click', function() {
					$('#ModalEdit #id').val(event.id);
					$('#ModalEdit #title').val(event.title);
					$('#ModalEdit #description').val(event.description);
					$('#ModalEdit #color').val(event.color);
					$('#ModalEdit').modal('show');
				});
			},
```

Anyway, thank you for your quick reply!

**Comment by waldronmatt** [comment]
Thank you for sharing, - it may be beneficial to implement your proposed single click to edit events similar to adding events for a better UI experience. 

@inside-shellshock can you branch off my master and submit a pull request with that change?

**Comment by waldronmatt** [comment]
Closing this issue with your PR merged. If this doesn't fix mobile editing feel free to reopen.
